// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbjbqkdzpjaivozdwutt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtiamJxa2R6cGphaXZvemR3dXR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwODQxNTMsImV4cCI6MjA2MTY2MDE1M30.V8hjVhC7HZi1CxHU_ApheB_rbjqbA-CweihsDiClQO8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);